// GENERATED by scratchpad/gen_layout.py (MASTER-5 Tasks 26 and 48). Every screen that opens without arguments
// fits a 360 x 640 phone at 1.3x text, light and dark, with an empty database (the empty state).
import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
import 'package:firebase_auth_mocks/firebase_auth_mocks.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:transport_app/core/l10n/l10n.dart';
import 'package:transport_app/core/services/backend.dart';
import 'package:transport_app/core/theme/app_theme.dart';
import 'package:transport_app/admin/admin_assistant_screen.dart';
import 'package:transport_app/admin/admin_claims_screen.dart';
import 'package:transport_app/admin/admin_config_screen.dart';
import 'package:transport_app/admin/admin_dashboard_screen.dart';
import 'package:transport_app/admin/admin_demo_screen.dart';
import 'package:transport_app/admin/admin_driver_rewards_screen.dart';
import 'package:transport_app/admin/admin_features_screen.dart';
import 'package:transport_app/admin/admin_feedback_screen.dart';
import 'package:transport_app/admin/admin_fraud_cases_screen.dart';
import 'package:transport_app/admin/admin_health_screen.dart';
import 'package:transport_app/admin/admin_lists.dart';
import 'package:transport_app/admin/admin_offers_screen.dart';
import 'package:transport_app/admin/admin_payouts_screen.dart';
import 'package:transport_app/admin/admin_rating_burst_screen.dart';
import 'package:transport_app/admin/admin_rating_flags_screen.dart';
import 'package:transport_app/admin/admin_signals_screen.dart';
import 'package:transport_app/admin/admin_supply_demand_screen.dart';
import 'package:transport_app/admin/admin_templates_screen.dart';
import 'package:transport_app/admin/admin_unit_economics_screen.dart';
import 'package:transport_app/admin/admin_verification_screen.dart';
import 'package:transport_app/admin/admin_violations_screen.dart';
import 'package:transport_app/admin/flagged_users_screen.dart';
import 'package:transport_app/auth/banned_screen.dart';
import 'package:transport_app/auth/customer_login_screen.dart';
import 'package:transport_app/auth/customer_profile_setup_screen.dart';
import 'package:transport_app/auth/driver_consent_screen.dart';
import 'package:transport_app/auth/driver_kyc_screen.dart';
import 'package:transport_app/auth/driver_login_screen.dart';
import 'package:transport_app/auth/driver_pending_screen.dart';
import 'package:transport_app/auth/driver_profile_setup_screen.dart';
import 'package:transport_app/auth/fleet_profile_setup_screen.dart';
import 'package:transport_app/auth/role_selection_screen.dart';
import 'package:transport_app/core/network/network_screen.dart';
import 'package:transport_app/core/safety/emergency_contacts_screen.dart';
import 'package:transport_app/core/settings/account_deletion_screen.dart';
import 'package:transport_app/core/settings/account_tools_screens.dart';
import 'package:transport_app/core/settings/devices_screen.dart';
import 'package:transport_app/core/settings/feedback_screen.dart';
import 'package:transport_app/core/settings/help_screen.dart';
import 'package:transport_app/core/settings/onboarding_screen.dart';
import 'package:transport_app/core/support/support_screens.dart';
import 'package:transport_app/core/widgets/app_control_gate.dart';
import 'package:transport_app/customer/bulk_post_screen.dart';
import 'package:transport_app/customer/business_hub_screen.dart';
import 'package:transport_app/customer/business_screen.dart';
import 'package:transport_app/customer/business_statement_screen.dart';
import 'package:transport_app/customer/business_team_screen.dart';
import 'package:transport_app/customer/customer_analytics_screen.dart';
import 'package:transport_app/customer/customer_home_screen.dart';
import 'package:transport_app/customer/my_drivers_screen.dart';
import 'package:transport_app/customer/offers_screen.dart';
import 'package:transport_app/customer/post_load_screen.dart';
import 'package:transport_app/customer/route_report_screen.dart';
import 'package:transport_app/customer/shipments_screen.dart';
import 'package:transport_app/customer/spending_screen.dart';
import 'package:transport_app/customer/templates_screen.dart';
import 'package:transport_app/customer/truck_board_screen.dart';
import 'package:transport_app/driver/add_vehicle_screen.dart';
import 'package:transport_app/driver/city_demand_screen.dart';
import 'package:transport_app/driver/driver_analytics_screen.dart';
import 'package:transport_app/driver/driver_home_screen.dart';
import 'package:transport_app/driver/driver_rewards_screen.dart';
import 'package:transport_app/driver/empty_trucks_screen.dart';
import 'package:transport_app/driver/favourite_routes_screen.dart';
import 'package:transport_app/driver/my_vehicles_screen.dart';
import 'package:transport_app/driver/simple_home_screen.dart';
import 'package:transport_app/driver/wallet_screen.dart';
import 'package:transport_app/fleet/fleet_analytics_screen.dart';
import 'package:transport_app/fleet/fleet_drivers_screen.dart';
import 'package:transport_app/fleet/fleet_home_screen.dart';
import 'package:transport_app/fleet/fleet_vehicles_screen.dart';
import 'package:transport_app/fleet/transporter_books_screen.dart';
import 'package:transport_app/fleet/transporter_fleet_screen.dart';
import 'package:transport_app/fleet/transporter_loads_screen.dart';
import 'package:transport_app/fleet/transporter_profile_screen.dart';
import 'package:transport_app/fleet/transporter_trips_screen.dart';

import 'test_utils.dart';

final Map<String, Widget Function()> _screens = {
  'AdminAssistantScreen': () => const AdminAssistantScreen(),
  'AdminClaimsScreen': () => const AdminClaimsScreen(),
  'AdminConfigScreen': () => const AdminConfigScreen(),
  'AdminDashboardScreen': () => const AdminDashboardScreen(),
  'AdminAnalyticsScreen': () => const AdminAnalyticsScreen(),
  'AdminDemoScreen': () => const AdminDemoScreen(),
  'AdminDriverRewardsScreen': () => const AdminDriverRewardsScreen(),
  'IncentiveEditScreen': () => const IncentiveEditScreen(),
  'AdminFeaturesScreen': () => const AdminFeaturesScreen(),
  'AdminFeedbackScreen': () => const AdminFeedbackScreen(),
  'AdminFraudCasesScreen': () => const AdminFraudCasesScreen(),
  'AdminHealthScreen': () => const AdminHealthScreen(),
  'AdminUsersScreen': () => const AdminUsersScreen(),
  'AdminVehiclesScreen': () => const AdminVehiclesScreen(),
  'AdminLoadsScreen': () => const AdminLoadsScreen(),
  'AdminBookingsScreen': () => const AdminBookingsScreen(),
  'AdminTicketsScreen': () => const AdminTicketsScreen(),
  'AdminSosScreen': () => const AdminSosScreen(),
  'AdminReportsScreen': () => const AdminReportsScreen(),
  'AdminAuditScreen': () => const AdminAuditScreen(),
  'AdminDeletionRequestsScreen': () => const AdminDeletionRequestsScreen(),
  'AdminOffersScreen': () => const AdminOffersScreen(),
  'PromoEditScreen': () => const PromoEditScreen(),
  'AdminPayoutsScreen': () => const AdminPayoutsScreen(),
  'AdminRatingBurstScreen': () => const AdminRatingBurstScreen(),
  'AdminRatingFlagsScreen': () => const AdminRatingFlagsScreen(),
  'AdminSignalsScreen': () => const AdminSignalsScreen(),
  'AdminSupplyDemandScreen': () => const AdminSupplyDemandScreen(),
  'AdminTemplatesScreen': () => const AdminTemplatesScreen(),
  'AdminUnitEconomicsScreen': () => const AdminUnitEconomicsScreen(),
  'AdminVerificationScreen': () => const AdminVerificationScreen(),
  'AdminViolationsScreen': () => const AdminViolationsScreen(),
  'FlaggedUsersScreen': () => const FlaggedUsersScreen(),
  'BannedScreen': () => const BannedScreen(),
  'CustomerLoginScreen': () => const CustomerLoginScreen(),
  'CustomerProfileSetupScreen': () => const CustomerProfileSetupScreen(),
  'DriverConsentScreen': () => const DriverConsentScreen(),
  'DriverKycScreen': () => const DriverKycScreen(),
  'DriverLoginScreen': () => const DriverLoginScreen(),
  'DriverPendingScreen': () => const DriverPendingScreen(),
  'DriverProfileSetupScreen': () => const DriverProfileSetupScreen(),
  'FleetProfileSetupScreen': () => const FleetProfileSetupScreen(),
  'RoleSelectionScreen': () => const RoleSelectionScreen(),
  'NetworkScreen': () => const NetworkScreen(),
  'EmergencyContactsScreen': () => const EmergencyContactsScreen(),
  'AccountDeletionScreen': () => const AccountDeletionScreen(),
  'LinkedAccountsScreen': () => const LinkedAccountsScreen(),
  'DataExportScreen': () => const DataExportScreen(),
  'PhoneChangeScreen': () => const PhoneChangeScreen(),
  'DevicesScreen': () => const DevicesScreen(),
  'FeedbackScreen': () => const FeedbackScreen(),
  'HelpScreen': () => const HelpScreen(),
  'OnboardingScreen': () => const OnboardingScreen(),
  'SupportHomeScreen': () => const SupportHomeScreen(),
  'NewTicketScreen': () => const NewTicketScreen(),
  'ForceUpdateScreen': () => const ForceUpdateScreen(),
  'MaintenanceScreen': () => const MaintenanceScreen(),
  'BulkPostScreen': () => const BulkPostScreen(),
  'BusinessHubScreen': () => const BusinessHubScreen(),
  'BusinessScreen': () => const BusinessScreen(),
  'BusinessStatementScreen': () => const BusinessStatementScreen(),
  'BusinessTeamScreen': () => const BusinessTeamScreen(),
  'CustomerAnalyticsScreen': () => const CustomerAnalyticsScreen(),
  'CustomerHomeScreen': () => const CustomerHomeScreen(),
  'MyDriversScreen': () => const MyDriversScreen(),
  'OffersScreen': () => const OffersScreen(),
  'PostLoadScreen': () => const PostLoadScreen(),
  'RouteReportScreen': () => const RouteReportScreen(),
  'ShipmentsScreen': () => const ShipmentsScreen(),
  'NewShipmentScreen': () => const NewShipmentScreen(),
  'SpendingScreen': () => const SpendingScreen(),
  'TemplatesScreen': () => const TemplatesScreen(),
  'TruckBoardScreen': () => const TruckBoardScreen(),
  'MyTruckRequestsScreen': () => const MyTruckRequestsScreen(),
  'AddVehicleScreen': () => const AddVehicleScreen(),
  'CityDemandScreen': () => const CityDemandScreen(),
  'DriverAnalyticsScreen': () => const DriverAnalyticsScreen(),
  'DriverHomeScreen': () => const DriverHomeScreen(),
  'DriverRewardsScreen': () => const DriverRewardsScreen(),
  'EmptyTrucksScreen': () => const EmptyTrucksScreen(),
  'FavouriteRoutesScreen': () => const FavouriteRoutesScreen(),
  'MyVehiclesScreen': () => const MyVehiclesScreen(),
  'SimpleLoadsScreen': () => const SimpleLoadsScreen(),
  'SimpleTripsScreen': () => const SimpleTripsScreen(),
  'SimpleMoneyScreen': () => const SimpleMoneyScreen(),
  'WalletScreen': () => const WalletScreen(),
  'FleetAnalyticsScreen': () => const FleetAnalyticsScreen(),
  'FleetDriversScreen': () => const FleetDriversScreen(),
  'FleetHomeScreen': () => const FleetHomeScreen(),
  'FleetVehiclesScreen': () => const FleetVehiclesScreen(),
  'TransporterBooksScreen': () => const TransporterBooksScreen(),
  'TransporterFleetScreen': () => const TransporterFleetScreen(),
  'TransporterLoadsScreen': () => const TransporterLoadsScreen(),
  'TransporterProfileScreen': () => const TransporterProfileScreen(),
  'TransporterTripsScreen': () => const TransporterTripsScreen(),
};

void main() {
  // SplashScreen is left out: it starts Firebase and navigates by itself (covered by the auth tests).
  for (final (lang, dark) in [(AppLanguage.english, false), (AppLanguage.english, true), (AppLanguage.tamil, false), (AppLanguage.urdu, true)]) {
    for (final e in _screens.entries) {
      testWidgets('${e.key} fits 360x640 at 1.3x text (${lang.name}, ${dark ? 'dark' : 'light'})', (tester) async {
        tester.view.physicalSize = const Size(360, 640);
        tester.view.devicePixelRatio = 1;
        addTearDown(tester.view.reset);
        SharedPreferences.setMockInitialValues({});
        Backend.useFakes(db: FakeFirebaseFirestore(), uid: () => 'u1', auth: () => MockFirebaseAuth(signedIn: true, mockUser: MockUser(uid: 'u1', phoneNumber: '+919999999999')));
        languageNotifier.value = lang;
        addTearDown(() => languageNotifier.value = AppLanguage.english);
        AppPalette.current = dark ? AppPalette.dark : AppPalette.light;
        await tester.pumpWidget(LanguageScope(
          notifier: languageNotifier,
          child: MaterialApp(
            theme: AppTheme.build(Brightness.light),
            darkTheme: AppTheme.build(Brightness.dark),
            themeMode: dark ? ThemeMode.dark : ThemeMode.light,
            builder: (context, c) => Directionality(textDirection: lang.textDirection, child: MediaQuery(data: MediaQuery.of(context).copyWith(textScaler: const TextScaler.linear(1.3)), child: c!)),
            home: e.value(),
          ),
        ));
        await settle(tester);
        expect(tester.takeException(), isNull);
      });
    }
  }
}
