// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoJNhxsq71Ct8MefH5vuakDRTwhY_9wWQ',
    appId: '1:50010549629:web:2a8533e2956716ccbb7014',
    messagingSenderId: '50010549629',
    projectId: 'loadgo-defc2',
    authDomain: 'loadgo-defc2.firebaseapp.com',
    storageBucket: 'loadgo-defc2.firebasestorage.app',
    measurementId: 'G-8534L1GD3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAphUamFEzb94QGtzL4rVmxgsUTaEyvtQk',
    appId: '1:50010549629:android:5626866547a4a72cbb7014',
    messagingSenderId: '50010549629',
    projectId: 'loadgo-defc2',
    storageBucket: 'loadgo-defc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClsnnKaKouKvk2spZg1Az5ozloj1Pqc94',
    appId: '1:50010549629:ios:ec3435ebb1bb29f3bb7014',
    messagingSenderId: '50010549629',
    projectId: 'loadgo-defc2',
    storageBucket: 'loadgo-defc2.firebasestorage.app',
    iosBundleId: 'com.example.transportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClsnnKaKouKvk2spZg1Az5ozloj1Pqc94',
    appId: '1:50010549629:ios:ec3435ebb1bb29f3bb7014',
    messagingSenderId: '50010549629',
    projectId: 'loadgo-defc2',
    storageBucket: 'loadgo-defc2.firebasestorage.app',
    iosBundleId: 'com.example.transportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoJNhxsq71Ct8MefH5vuakDRTwhY_9wWQ',
    appId: '1:50010549629:web:5ccaab96ed6f0702bb7014',
    messagingSenderId: '50010549629',
    projectId: 'loadgo-defc2',
    authDomain: 'loadgo-defc2.firebaseapp.com',
    storageBucket: 'loadgo-defc2.firebasestorage.app',
    measurementId: 'G-KVYWTXQM9H',
  );
}
