# Regenerates test/layout_all_screens_test.dart from every *Screen / *View / *Page that opens without arguments.
# Usage (from the repo root): python3 tool/gen_layout_test.py [file-with-class-names-to-skip]
# SplashScreen is skipped by hand (see the comment in the generated file).
import re,glob,sys
skip=set(open(sys.argv[1]).read().split()) if len(sys.argv)>1 else set()
out=[]
for f in sorted(glob.glob('lib/**/*.dart',recursive=True)):
    s=open(f).read()
    for m in re.finditer(r'class (\w+(?:Screen|View|Page)) extends (?:StatefulWidget|StatelessWidget) \{(.*?)\n\}',s,re.S):
        name,body=m.group(1),m.group(2)
        c=re.search(r'(const )?'+name+r'\(\{([^}]*)\}\)',body)
        if c is None or 'required' in c.group(2): continue
        out.append((f,name,bool(c.group(1))))
out=[o for o in out if o[1] not in skip]
imports=sorted({f[4:] for f,_,_ in out})
L=["// GENERATED by scratchpad/gen_layout.py (MASTER-5 Tasks 26 and 48). Every screen that opens without arguments",
"// fits a 360 x 640 phone at 1.3x text, light and dark, with an empty database (the empty state).",
"import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';",
"import 'package:firebase_auth_mocks/firebase_auth_mocks.dart';",
"import 'package:flutter/material.dart';",
"import 'package:flutter_test/flutter_test.dart';",
"import 'package:shared_preferences/shared_preferences.dart';",
"import 'package:transport_app/core/l10n/l10n.dart';",
"import 'package:transport_app/core/services/backend.dart';",
"import 'package:transport_app/core/theme/app_theme.dart';",
]
for i in imports: L.append(f"import 'package:transport_app/{i}';")
L+=["","import 'test_utils.dart';","","final Map<String, Widget Function()> _screens = {"]
for f,n,const in out:
    if n in skip: continue
    L.append(f"  '{n}': () => {'const ' if const else ''}{n}(),")
L+=["};","","void main() {",
"  // SplashScreen is left out: it starts Firebase and navigates by itself (covered by the auth tests).",
"  for (final (lang, dark) in [(AppLanguage.english, false), (AppLanguage.english, true), (AppLanguage.tamil, false), (AppLanguage.urdu, true)]) {",
"    for (final e in _screens.entries) {",
"      testWidgets('${e.key} fits 360x640 at 1.3x text (${lang.name}, ${dark ? 'dark' : 'light'})', (tester) async {",
"        tester.view.physicalSize = const Size(360, 640);",
"        tester.view.devicePixelRatio = 1;",
"        addTearDown(tester.view.reset);",
"        SharedPreferences.setMockInitialValues({});",
"        Backend.useFakes(db: FakeFirebaseFirestore(), uid: () => 'u1', auth: () => MockFirebaseAuth(signedIn: true, mockUser: MockUser(uid: 'u1', phoneNumber: '+919999999999')));",
"        languageNotifier.value = lang;",
"        addTearDown(() => languageNotifier.value = AppLanguage.english);",
"        AppPalette.current = dark ? AppPalette.dark : AppPalette.light;",
"        await tester.pumpWidget(LanguageScope(",
"          notifier: languageNotifier,",
"          child: MaterialApp(",
"            theme: AppTheme.build(Brightness.light),",
"            darkTheme: AppTheme.build(Brightness.dark),",
"            themeMode: dark ? ThemeMode.dark : ThemeMode.light,",
"            builder: (context, c) => Directionality(textDirection: lang.textDirection, child: MediaQuery(data: MediaQuery.of(context).copyWith(textScaler: const TextScaler.linear(1.3)), child: c!)),",
"            home: e.value(),",
"          ),",
"        ));",
"        await settle(tester);",
"        expect(tester.takeException(), isNull);",
"      });",
"    }",
"  }",
"}"]
open('test/layout_all_screens_test.dart','w').write('\n'.join(L)+'\n')
print(len(out))
