/// Admin list search, saved filters, paging and export (MASTER-5 Task 38). Order: en, hi, hinglish, kn, ta, te, mr, gu, bn, pa, ks, ur.
const Map<String, List<String>> adminListStrings = {
  'adminSearchHint': ['Search this list', 'इस सूची में खोजें', 'Is list mein dhoondhein', 'ಈ ಪಟ್ಟಿಯಲ್ಲಿ ಹುಡುಕಿ', 'இந்தப் பட்டியலில் தேடுங்கள்', 'ఈ జాబితాలో వెతకండి', 'या यादीत शोधा', 'આ યાદીમાં શોધો', 'এই তালিকায় খুঁজুন', 'ਇਸ ਸੂਚੀ ਵਿੱਚ ਲੱਭੋ', 'یمہ لسٹہٕ منز ژارِو', 'اس فہرست میں تلاش کریں'],
  'adminSavedFilters': ['Saved filters', 'सहेजे फ़िल्टर', 'Saved filters', 'ಉಳಿಸಿದ ಫಿಲ್ಟರ್‌ಗಳು', 'சேமித்த வடிப்பான்கள்', 'సేవ్ చేసిన ఫిల్టర్లు', 'जतन केलेले फिल्टर', 'સાચવેલા ફિલ્ટર', 'সংরক্ষিত ফিল্টার', 'ਸੰਭਾਲੇ ਫਿਲਟਰ', 'محفوظ فِلٹر', 'محفوظ فلٹرز'],
  'adminSaveFilter': ['Save this search', 'यह खोज सहेजें', 'Yeh search save karein', 'ಈ ಹುಡುಕಾಟ ಉಳಿಸಿ', 'இந்தத் தேடலைச் சேமிக்கவும்', 'ఈ శోధనను సేవ్ చేయండి', 'ही शोध जतन करा', 'આ શોધ સાચવો', 'এই অনুসন্ধান সংরক্ষণ করুন', 'ਇਹ ਖੋਜ ਸੰਭਾਲੋ', 'یہ ژارٕن محفوظ کرِو', 'یہ تلاش محفوظ کریں'],
  'adminShowMore': ['Show 50 more', '50 और दिखाएँ', '50 aur dikhayein', 'ಇನ್ನೂ 50 ತೋರಿಸಿ', 'மேலும் 50 காட்டு', 'మరో 50 చూపించు', 'आणखी 50 दाखवा', 'વધુ 50 બતાવો', 'আরও ৫০টি দেখান', '50 ਹੋਰ ਦਿਖਾਓ', 'مزید 50 ہیرِو', 'مزید 50 دکھائیں'],
  'adminShowing': ['Showing {n} of {total}', '{total} में से {n} दिख रहे हैं', '{total} mein se {n} dikh rahe hain', '{total} ರಲ್ಲಿ {n} ತೋರಿಸಲಾಗಿದೆ', '{total} இல் {n} காட்டப்படுகிறது', '{total} లో {n} చూపుతోంది', '{total} पैकी {n} दाखवत आहे', '{total} માંથી {n} બતાવે છે', '{total}-এর মধ্যে {n} দেখাচ্ছে', '{total} ਵਿੱਚੋਂ {n} ਦਿਖ ਰਹੇ ਹਨ', '{total} منزہ {n} ہیوٚ', '{total} میں سے {n} دکھائے جا رہے ہیں'],
  'adminExportCsv': ['Export CSV', 'CSV निर्यात करें', 'CSV export karein', 'CSV ರಫ್ತು ಮಾಡಿ', 'CSV ஏற்றுமதி', 'CSV ఎగుమతి', 'CSV निर्यात', 'CSV નિકાસ', 'CSV রপ্তানি', 'CSV ਬਰਾਮਦ', 'CSV ایکسپورٹ', 'CSV برآمد کریں'],
};
