/// Verification badge and profile strings. Order: en, hi, hinglish, kn, ta, te, mr, gu, bn, pa, ks, ur.
const Map<String, List<String>> badgeStrings = {
  'badgeOtpVerified': ['Verified by OTP', 'OTP से सत्यापित', 'OTP se verified', 'OTP ಮೂಲಕ ಪರಿಶೀಲಿಸಲಾಗಿದೆ', 'OTP மூலம் சரிபார்க்கப்பட்டது', 'OTP ద్వారా ధృవీకరించబడింది', 'OTP द्वारे पडताळले', 'OTP દ્વારા ચકાસાયેલ', 'OTP দ্বারা যাচাইকৃত', 'OTP ਰਾਹੀਂ ਤਸਦੀਕ', 'OTP ہیتھ تصدیق شُد', 'OTP سے تصدیق شدہ'],
  'badgeReviewed': ['Reviewed by LoadGo', 'LoadGo द्वारा समीक्षित', 'LoadGo ne review kiya', 'LoadGo ಪರಿಶೀಲಿಸಿದೆ', 'LoadGo மதிப்பாய்வு செய்தது', 'LoadGo సమీక్షించింది', 'LoadGo ने तपासले', 'LoadGo દ્વારા સમીક્ષા', 'LoadGo পর্যালোচনা করেছে', 'LoadGo ਵੱਲੋਂ ਸਮੀਖਿਆ', 'LoadGo ہیتھ نظرثانی', 'LoadGo کی طرف سے جائزہ'],
  'badgeMissing': ['Not provided', 'नहीं दिया गया', 'Nahi diya gaya', 'ನೀಡಿಲ್ಲ', 'வழங்கவில்லை', 'ఇవ్వలేదు', 'दिलेले नाही', 'આપેલ નથી', 'দেওয়া হয়নি', 'ਦਿੱਤਾ ਨਹੀਂ', 'نہ دتُ', 'فراہم نہیں'],
  'badgeReviewedManual': ['Reviewed by a LoadGo admin', 'LoadGo एडमिन द्वारा समीक्षित', 'LoadGo admin ne review kiya', 'LoadGo ಅಡ್ಮಿನ್ ಪರಿಶೀಲಿಸಿದ್ದಾರೆ', 'LoadGo நிர்வாகி மதிப்பாய்வு செய்தார்', 'LoadGo అడ్మిన్ సమీక్షించారు', 'LoadGo अ‍ॅडमिनने तपासले', 'LoadGo એડમિને સમીક્ષા કરી', 'LoadGo অ্যাডমিন পর্যালোচনা করেছেন', 'LoadGo ਐਡਮਿਨ ਨੇ ਸਮੀਖਿਆ ਕੀਤੀ', 'LoadGo ایڈمنن کرِ نظرثانی', 'LoadGo ایڈمن نے جائزہ لیا'],
  'badgeReviewedOn': ['Reviewed by a LoadGo admin on {date}', '{date} को LoadGo एडमिन द्वारा समीक्षित', '{date} ko LoadGo admin ne review kiya', '{date} ರಂದು LoadGo ಅಡ್ಮಿನ್ ಪರಿಶೀಲಿಸಿದ್ದಾರೆ', '{date} அன்று LoadGo நிர்வாகி மதிப்பாய்வு செய்தார்', '{date} న LoadGo అడ్మిన్ సమీక్షించారు', '{date} रोजी LoadGo अ‍ॅडमिनने तपासले', '{date} ના રોજ LoadGo એડમિને સમીક્ષા કરી', '{date} তারিখে LoadGo অ্যাডমিন পর্যালোচনা করেছেন', '{date} ਨੂੰ LoadGo ਐਡਮਿਨ ਨੇ ਸਮੀਖਿਆ ਕੀਤੀ', '{date} LoadGo ایڈمنن کرِ نظرثانی', '{date} کو LoadGo ایڈمن نے جائزہ لیا'],
  'showNumbers': ['Show numbers', 'नंबर दिखाएँ', 'Numbers dikhayein', 'ಸಂಖ್ಯೆಗಳನ್ನು ತೋರಿಸಿ', 'எண்களைக் காட்டு', 'నంబర్లు చూపించు', 'क्रमांक दाखवा', 'નંબર બતાવો', 'নম্বর দেখান', 'ਨੰਬਰ ਦਿਖਾਓ', 'نمبر ؤچھناو', 'نمبر دکھائیں'],
  'hideNumbers': ['Hide numbers', 'नंबर छिपाएँ', 'Numbers chhupayein', 'ಸಂಖ್ಯೆಗಳನ್ನು ಮರೆಮಾಡಿ', 'எண்களை மறை', 'నంబర్లు దాచు', 'क्रमांक लपवा', 'નંબર છુપાવો', 'নম্বর লুকান', 'ਨੰਬਰ ਲੁਕਾਓ', 'نمبر لُکناو', 'نمبر چھپائیں'],
  'verificationTitle': ['Verification', 'सत्यापन', 'Verification', 'ಪರಿಶೀಲನೆ', 'சரிபார்ப்பு', 'ధృవీకరణ', 'पडताळणी', 'ચકાસણી', 'যাচাই', 'ਤਸਦੀਕ', 'تصدیق', 'تصدیق'],
  'profileVehicles': ['{n} vehicle(s)', '{n} वाहन', '{n} vehicle', '{n} ವಾಹನ(ಗಳು)', '{n} வாகனம்(ங்கள்)', '{n} వాహనం(లు)', '{n} वाहन', '{n} વાહન', '{n}টি গাড়ি', '{n} ਵਾਹਨ', '{n} گاڑی', '{n} گاڑیاں'],
  'profileLanguage': ['Language: {lang}', 'भाषा: {lang}', 'Language: {lang}', 'ಭಾಷೆ: {lang}', 'மொழி: {lang}', 'భాష: {lang}', 'भाषा: {lang}', 'ભાષા: {lang}', 'ভাষা: {lang}', 'ਭਾਸ਼ਾ: {lang}', 'زبان: {lang}', 'زبان: {lang}'],
};
